Redo argument parsing and add `log` subcommand
VanuPhantom/skrive pull request #5
Opened 2024-02-11 22:18 UTC by freyacodes

* Added `argparse` as a new library to handle command line arguments
* Moved specification of the doses file to the new `-f` flag, as opposed to the first argument of the program
* Added the `log` subcommand. Acts as a shortcut with 0 arguments. 
* Added documentation for the above

2024-02-11 23:11 UTC, VanuPhantom requested changes
The changes look good. I have found some minor stylistic issues, once these have been resolved, we can merge the PR.

2024-02-11 23:11 UTC, VanuPhantom commented on README.md
> +skrive log [-f path to doses.dat] <quantity> <substance> <route>
```suggestion
skrive log [-f path to doses.dat] [<quantity> <substance> <route>]
```

These parameters are optional as a group.

2024-02-11 23:11 UTC, VanuPhantom commented on args.go
I suggest renaming this file to `arguments.go`.

2024-02-11 23:11 UTC, VanuPhantom commented on args.go
> +var fileArg = parser.String("f", "file", &argparse.Options{Required: false, Help: "Set dosage file path"})
```suggestion
var fileArg = parser.String("f", "file", &argparse.Options{Required: false, Help: "Set the doses file path"})
```

2024-02-11 23:11 UTC, VanuPhantom commented on args.go
> +	// Our custom help flag is used for properly called printHelp()
Can you clarify what you meant with this comment?

2024-02-11 23:11 UTC, VanuPhantom commented on args.go
> +	parser.NewCommand("<blank>", "Open interactive menu")
```suggestion
	parser.NewCommand("<blank>", "Open the TUI")
```

I suggest we refer to the UI as "the TUI" instead of "interactive menu".

2024-02-11 23:11 UTC, VanuPhantom commented on main.go
> +	if parseErr != nil {
```suggestion
	if parseErr := logic.Setup; parseErr != nil {
```

I suggest inlining the variable definition to make this code more readable and limit the variable's scope

2024-02-11 23:11 UTC, VanuPhantom commented on main.go
> +		return
```suggestion
	exitIfError(err)
}

func handleSubcommands() {
	switch *subcommand {
	case "log":
		if len(positionalArguments) == 0 {
			// Handled in Bubbletea initialization code
			return
		}
		exitIfError(log.Invoke(positionalArguments))
	}
	os.Exit(0)
}

func exitIfError(err error) {
	if err == nil {
		return
```

`handleIfError` isn't a very descriptive name. I suggest renaming the function to `exitIfError`

2024-02-12 16:08 UTC, freyacodes commented on args.go
> +	// Our custom help flag is used for properly called printHelp()
`argparse` implements a `-h` and `--help` flag by default. When that is invoked, the library prints out incomplete information as it is unaware of the subcommands defined in `printHelp()`. To fix this, we implement our own flag instead.

This comment is incomplete, I will update it

2024-02-12 16:18 UTC, VanuPhantom approved these changes
Quite a drastic departure from the original simplicity, but I like it! Good work :)

2024-02-12 16:19 UTC, merged